name: Build and Test C++

on: [push, pull_request]

jobs:
  valgrind:
    name: valgrind ubuntu
    runs-on: ubuntu-20.04
    steps:

      - name: Cancel previous runs on the same branch
        if: ${{ github.ref != 'refs/heads/main' }}
        uses: styfle/cancel-workflow-action@0.7.0
        with:
          access_token: ${{ github.token }}
      
      - name: Checkout code
        uses: actions/checkout@v2

      - name: cmake, RunTests, and valgrind on ubuntu-20.04
        run: |
          sudo apt update
          sudo apt-get install valgrind -y
          mkdir build
          cd build
          cmake ../
          cmake --build . -- -j 6
          ctest -j 6 --output-on-failure
          valgrind --leak-check=full --show-leak-kinds=all --errors-for-leak-kinds=all ctest -j 6 --output-on-failure

  

  windows:
    name: Windows Latest
    runs-on: windows-latest
    steps:

    - name: Cancel previous runs on the same branch
      if: ${{ github.ref != 'refs/heads/main' }}
      uses: styfle/cancel-workflow-action@0.7.0
      with:
        access_token: ${{ github.token }}

    - name: Checkout code
      uses: actions/checkout@v2

    - name: cmake, RunTests with Windows
      run: |
        mkdir build-win
        cd build-win
        cmake ..
        cmake --build . --config Release -j 6
        ctest -C Release -j 6
